name: Weekly Helm Chart Check

on:
  workflow_dispatch:
  #schedule:
   # - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday

jobs:
  check-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run Helm Update Check Script
        run: |
          chmod +x ./helmcheckrelease.sh
          ./helmcheckrelease.sh
